#!/bin/bash

# Ensure that the following lines match the base PKGBUILD

export retcode=0
for term in ^pkgname\= ^replaces\= ^pkgver\= ^epoch\= ^pkgdesc\= ^url\= ^license\= ../LICENSE; do
    current="$(grep -E "${term}" ./PKGBUILD)"
    reference="$(grep -E "${term}" /opt/aninix/Uniglot/pacman/PKGBUILD)"
    diff -w --color=always <(printf "${current}") <(printf "${reference}")
    export retcode="$(( $retcode || $? ))";
    if [ "$retcode" != 0 ]; then
        echo "$term has delta."
        break;
    fi
done

if [ "$(basename "$PWD")" == 'Uniglot' ] && [ "$retcode" != 0 ]; then
    if [ ! -f /opt/aninix/Uniglot/pacman/PKGBUILD ]; then
        # Suppress output for this package when it isn't installed yet.
        echo $0
    else
        echo INFO: You have introduced delta for the PKGBUILD. You may need to update downstream projects.
        exit 0
    fi
elif [ "$retcode" != 0 ]; then
    echo ERROR: PKGBUILD is out of sync with AniNIX/Uniglot.
    exit 1
fi
