#!/bin/bash

if git ls-files | xargs --delimiter='\n' grep -irlE 'egrep' | grep -v 'Hooks/scripts.d/egrep' ; then
    echo 'Egrep has been deprecated as of GNU grep 3.8 -- replace `egrep` with `grep -E`.'
    echo https://www.gnu.org/software/grep/manual/grep.html
    exit 1
fi
