#!/bin/bash

# We don't want to commit data files, with the exceptions being our GPG public key and organization logo in PNG & ASCII format.
for file in `git ls-files | xargs -n 1 file | grep -Ev 'ASCII text|JSON|empty|Unicode text|symbolic link' | grep -vE '^Resources/logo.png|^Resources/ascii.txt|^Resources/public.gpg' | cut -f 1 -d :`; do
    if [ "$(du -k "${file}" | awk '{ print $1; }')" -gt 10 ]; then
        echo "These files need to be evaluated -- generally, don't commit data files to Git."
        echo "$result"
        exit 1
    fi
done
exit 0
