#!/bin/bash

# Run python3 tests

if [ -d venv ]; then
    source venv/bin/activate
elif [ -f requirements.txt ]; then
    python3 -m venv venv
    venv/bin/python3 -m pip install -r requirements.txt
fi
if [ -d tests/ ]; then
    python3 -m pytest
fi
