#!/bin/bash

# Sourced from https://github.com/git/git/blob/master/templates/hooks--pre-commit.sample

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against --
if [ $? -ne 0 ]; then
    echo The above lines have trailing whitespace. Run "sed -i 's/\s\+$//'" on the affected files.
    exit 1
fi
