#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Run all our checking scripts.
for script in $(find `dirname "$0"`/scripts.d -type f); do
    echo "Running ${script}"
    "$script"
    if [ $? -ne 0 ]; then
        echo "$script" failed checks.
        exit 1;
    fi
done
echo "Pre-commit checks passed."
